# Generated by Django 4.0.4 on 2022-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('s_stock', models.IntegerField()),
                ('m_stock', models.IntegerField()),
                ('l_stock', models.IntegerField()),
            ],
        ),
    ]
