# Generated by Django 4.0.4 on 2022-05-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cash', models.BinaryField()),
                ('delivery', models.BinaryField()),
                ('address', models.CharField(max_length=500)),
                ('postcode', models.CharField(max_length=4)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.food')),
            ],
        ),
    ]
