# Generated by Django 4.0.4 on 2022-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.CharField(default='phone num', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.BinaryField(default=False),
        ),
    ]
