# Generated by Django 4.0.4 on 2022-05-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('SML', 'Small'), ('MED', 'Medium'), ('LRG', 'Large')], default='SML', max_length=3)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='l_stock',
        ),
        migrations.RemoveField(
            model_name='food',
            name='m_stock',
        ),
        migrations.RemoveField(
            model_name='food',
            name='s_stock',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('CHICKEN', 'Chicken'), ('PORK', 'Pork'), ('BEEF', 'Beef'), ('SEAFOOD', 'Seafood'), ('VEGETABLE', 'Vegetable'), ('PASTA', 'Pasta'), ('SOUP', 'Soup'), ('DESSERT', 'Dessert')], default='CHICKEN', max_length=9),
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('parent_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.food_products')),
            ],
        ),
        migrations.AddField(
            model_name='food_products',
            name='parent_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.food'),
        ),
    ]
