# Generated by Django 4.0.4 on 2022-05-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_food_products_remove_food_l_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_products',
            new_name='food_product',
        ),
        migrations.RenameModel(
            old_name='order_items',
            new_name='order_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
    ]
